language: ruby
cache: bundler
sudo: false
rvm:
- 2.1
matrix:
    include:
        - rvm: 2.1
          env: JEKYLL_VERSION=3.03
    fast_finish: true

install:
  - bundle install

script: bundle exec rake site:deploy

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  secure: "ZjXcDUFYt8X0AuTFF0umjagz0rlS6u8t21BN8h9bdChnBl29ustIgmZfgMWxwFR6xPyKOgt2fhMs8sePZ+UL4AePw18Oqi90Xmu/m4GCZ7i8cXGlA/IoYXcVCCu3IZ+hDPFBBUjjvXTxL1vHj7m9BuNyCDPl/DbnXl2hW4iEXKQ="
